cc_library(
    name = "crossing_state",
    hdrs = [
        "crossing_state.h",
    ],
    srcs = [
        "crossing_state.cpp",
    ],
    deps = [
        "//mcts:mamcts",
    ],
    visibility = ["//visibility:public"],
)