cc_test(
    name = "cost_constrained_statistic_test",
    srcs = [
        "cost_constrained_statistic_test.cc",
        "cost_constrained_statistic_test_state.h"
    ],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//mcts:mamcts",
        "@gtest//:main",
    ],
)