cc_library(
    name = "mamcts",
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
    deps = 
    [
        "@com_github_glog_glog//:glog",
        "@boost//:functional",
        "@boost//:variant",
        "@google_or//ortools/linear_solver:linear_solver",
    ]
)