py_test(
  name = "py_crossing_state_test",
  srcs = ["py_crossing_state_test.py"],
  data = ['//python/bindings:mamcts.so'],
  imports = ['../../python/bindings'],
  deps=[
    "//environments:pyviewer"
  ]
)
